created_at: '2025-09-27T18:53:56.196500'
document:
  chunk_overlap: 200
  chunk_size: 1000
  document_directory: C:\source_code\raglish\test_docs
  exclude_patterns:
  - '*.tmp'
  - '*.log'
  - .*
  max_file_size: 52428800
  supported_formats:
  - pdf
  - docx
  - txt
  - md
llm:
  additional_params: {}
  api_key: null
  host: localhost:11434
  max_tokens: 1000
  model_name: llama2
  provider: ollama
  temperature: 0.7
updated_at: '2025-09-27T18:54:10.072817'
user:
  feedback_level: normal
  learning_level: intermediate
  native_language: korean
  preferred_topics: []
  session_timeout: 30
  target_language: english
version: 1.0.0
