created_at: '2025-09-27T23:33:41.687821'
document:
  chunk_overlap: 200
  chunk_size: 1000
  document_directory: C:\Users\user\Downloads\gscarr
  exclude_patterns:
  - '*.tmp'
  - '*.log'
  - .*
  max_file_size: 52428800
  supported_formats:
  - pdf
  - docx
  - txt
  - md
llm:
  additional_params: {}
  api_key: AIzaSyAZKoEPuAPgLWf1rOh_KeG35eWFLYFk_s4
  host: localhost:11434
  max_tokens: 1000
  model_name: gemini-2.5-flash
  provider: gemini
  temperature: 0.7
updated_at: '2025-09-27T23:39:23.364773'
user:
  feedback_level: normal
  learning_level: intermediate
  native_language: korean
  preferred_topics: []
  session_timeout: 30
  target_language: english
version: 1.0.0
